---
- name: Create linked VMs from Proxmox template
  hosts: localhost
  gather_facts: false
  vars:
    vm_count: 3
  tasks:
    - name: Create new VMs from template (linked clone)
      community.general.proxmox_kvm:
        api_host: "proxmox_host_ip"
        api_user: "root@pam"
        api_password: "password"
        node: "prox"
        clone: "ubuntu-template"        # The original VM template
        clone_type: linked             # Use linked clone (this is the magic part!)
        name: "kube-{{ item }}"         # VM names will be kube-1, kube-2, kube-3
        storage: "Storage4tb"          # The storage where the clones will reside
        memory: 4096                   # Memory in MB
        cores: 2                       # CPU cores
        sockets: 1                     # Number of sockets
        onboot: true                   # VM starts automatically
        nameservers:
          - "8.8.8.8"                 # DNS
        searchdomains:
          - "local"                   # Search domain
        boot: "cdn"                    # Boot method
        bootdisk: "scsi0"              # Disk to boot from
        timeout: 600                   # Wait for 10 minutes for the clone to complete
      loop: "{{ range(1, vm_count + 1) | list }}"
      loop_control:
        label: "{{ item }}"
