---
- name: Create Kubernetes VMs in Proxmox
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    proxmox_host: "10.0.0.2"
    proxmox_user: "root@pam"
    proxmox_password: "whatisthedeal"
    proxmox_node: "prox"
    template_name: "ubuntu-template"
    storage_name: "Storage4tb"
    vm_memory: 4096
    vm_cores: 2
    vm_sockets: 1
    cloud_user: "ubuntu"
    cloud_password: "whatisthedeal"
    gateway: "10.0.0.1"
    vm_list:
      - name: k4
        ip: "10.0.0.121"
      - name: k5
        ip: "10.0.0.122"

  tasks:

    - name: Clone VMs from template with static IPs
      community.proxmox.proxmox_kvm:
        api_host: "{{ proxmox_host }}"
        api_user: "{{ proxmox_user }}"
        api_password: "{{ proxmox_password }}"
        node: "{{ proxmox_node }}"
        clone: "{{ template_name }}"
        name: "{{ item.name }}"
        full: true
        storage: "{{ storage_name }}"
        memory: "{{ vm_memory }}"
        cores: "{{ vm_cores }}"
        sockets: "{{ vm_sockets }}"
        onboot: true
        ciuser: "{{ cloud_user }}"
        cipassword: "{{ cloud_password }}"
        net:
          net0: virtio,bridge=vmbr0
        ipconfig:
          ip: "{{ item.ip }}/24"
          gw: "{{ gateway }}"
      loop: "{{ vm_list }}"
      loop_control:
        label: "{{ item.name }}"

# PLAY 2 — Wait for SSH and add hosts dynamically
- name: Wait for VMs to be reachable
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: Wait for SSH to become available
      wait_for:
        host: "{{ item.ip }}"
        port: 22
        timeout: 7600
      loop: "{{ vm_list }}"

    - name: Add new VMs to Ansible inventory
      add_host:
        name: "{{ item.name }}"
        ansible_host: "{{ item.ip }}"
        ansible_user: ubuntu
      loop: "{{ vm_list }}"

# PLAY 3 — Configure the new VMs
- name: Configure hostnames and install Oh-My-Posh
  hosts: k4,k5
  become: true
  gather_facts: true

  tasks:
    - name: Set system hostname
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"

    - name: Update /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.1\.1'
        line: "127.0.1.1 {{ inventory_hostname }}"

    - name: Install prerequisites
      ansible.builtin.apt:
        name:
          - curl
          - wget
          - unzip
        state: present
        update_cache: yes

    - name: Install Oh My Posh
      ansible.builtin.shell: |
        curl -s https://ohmyposh.dev/install.sh | bash -s
        oh-my-posh font install Meslo
        mkdir -p ~/.poshthemes
        wget https://github.com/catppuccin/oh-my-posh/releases/latest/download/catppuccin.omp.json -O ~/.poshthemes/catppuccin.omp.json
        echo 'eval "$(oh-my-posh init bash --config ~/.poshthemes/catppuccin.omp.json)"' >> ~/.bashrc
      args:
        executable: /bin/bash
